### PR TITLE
fix empty fields on assets in preview mode

### LINKED ISSUE #145: Vault fails to sync in preview mode if there is an empty CDAAsset
com.contentful.vault.SyncException: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference

This exception is thrown when I try to sync vault in preview mode and there is a draft asset which is empty.

I create CDAClient for preview mode like this
CDAClient.builder().preview().setSpace(spaceType.spaceId).setToken(spaceType.getToken()).build()

It works as expected if there is no empty draft asset but fails if there is any.

### PR DESCRIPTION
**Pull request by mariobodemann**
closes #145

### CODE REVIEW

File: core/src/test/java/com/contentful/vault/ObserveTest.java [hunk 1]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright (C) 2015 Contentful GmbH
+ * Copyright (C) 2018 Contentful GmbH
```
Comment (Khaledgarbaya) [inline core/src/test/java/com/contentful/vault/ObserveTest.java]: shouldn't this be 2015 - 2018?

Comment (mariobodemann) [reply core/src/test/java/com/contentful/vault/ObserveTest.java]: Hmm, good question. Classically we always used current year for those headers.

Comment (mariobodemann) [reply core/src/test/java/com/contentful/vault/ObserveTest.java]: For consistency reasons, I'll just keep the header format how I have it everywhere else: One year, changed once a year ... :slightly_smiling_face:
